name: polygraphs
channels:
  - pytorch
  - dglteam
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - tqdm=4.64.1
  - fsspec
  - ipywidgets
  - pytorch=2.1.0
  - h5py
  - fsspec
  - matplotlib
  - seaborn
  - pylint
  - flake8
  - pyyaml
  - pandas
  - dgl
  - pydantic
  - torchdata
